alb:
  clusterName: "eks-backend"
  serviceAccountName: "aws-load-balancer-controller"
  #-- got from eksctl create iamserviceaccount --name=alb-ingress-controller
  # serviceAccountRole: "arn:aws:iam::335082366654:role/eksctl-eks-backend-addon-iamserviceaccount-ku-Role1-5iDhBkMznHDK"
  privateSubnets: subnet-07b5c7a948d741fbe,subnet-0702bc09bb6d370f1
  region: us-west-2
  vpcId: vpc-0d5fe5db59dd8bc11



